cache:
  type: DiskCache
  root: 'tmp/mapcache'

layers:    
  basic:
    type: MapServer
    mapfile: app/map/odamap.map
    layers: NIC2,NIC1
    maxresolution: 0.01991484375
    levels: 5
    extension: png
    metatile: true
    metabuffer: 0, 0
    bbox: 21, -27, 49, -10
  report:
    type: MapServer
    mapfile: app/map/reports.map
    layers: NIC1,NIC2,highlights
    maxresolution: 0.01991484375
    levels: 1
    extension: png
    metatile: true
    metabuffer: 0, 0
    bbox: 21, -27, 49, -10
